version: '3.8'
######################################################
# GRPC CLIENT
######################################################
networks:
  grpc-network:
    name: grpc-network

services:
  grpc_master:
    build:
      context: master/
    container_name: master
    networks:
      grpc-network:
        aliases:
          - server
    ports:
      - "8080:8080"
      - "6565:6565"

  grpc_secondary-1:
    container_name: secondary-1
    build:
      context: secondary-python/
    environment:
      PYTHONUNBUFFERED: 1
    command: python3 secondary.py
    networks:
      grpc-network:
        aliases:
          - secondary-1
    ports:
      - "6567:6567"

  grpc_secondary-2:
    container_name: secondary-2
    build:
      context: secondary-java/
    networks:
      grpc-network:
        aliases:
          - secondary-2
    ports:
      - "6568:6567"